### PR TITLE
Update harbour-concretemixer-sk.ts

### PR DESCRIPTION
**Pull request by okruhliak**
Add slovak translate

### CODE REVIEW

**Comment by poetaster** [comment]
Thank you very much! I'll do a release ASAP.

**Comment by okruhliak** [comment]
Thank you for the quick implementation of Slovak. 
Would it be possible to display the description on the schematic image (length, width, radius, ...) in the translated language?

**Comment by poetaster** [comment]
> Thank you for the quick implementation of Slovak. Would it be possible to display the description on the schematic image (length, width, radius, ...) in the translated language?

The images are just static at the moment (pngs) but I should be able to rebuild that. I'll make a ticket to that effect. Thanks again!

**Comment by poetaster** [comment]
https://github.com/poetaster/harbour-concretemixer/issues/7

**Pull request merged**
